<?php 
if( $this->loginEnable() == "1" && !$this->user_is_already_login() ){
  $belowLogin = $this->getBelowLogin();
  $ApiKey = trim($this->getApikey());
  $ApiSecrete = trim($this->getApiSecret());
  $loginRadiusTitle = trim( $this->getLoginRadiusTitle() );
  $UserAuth = $this->getApiResult($ApiKey, $ApiSecrete);
  if ($belowLogin == 1) {
    echo '<div class="block" style="margin-top:15px"><div class="block-title"><strong><span>Social Login</span></strong></div><div class="block-content"><p class="empty">';
		if($ApiKey == "" && $ApiSecrete == ""){
			echo '<p style ="color:red;">To activate your plugin, please log in to LoginRadius and get API Key & Secret. Web: <b><a href ="http://www.loginradius.com" target = "_blank">www.LoginRadius.com</a></b></p>';
		}elseif ($UserAuth == false) {
	    echo '<p style ="color:red;">Your LoginRadius API key and secret is not valid, please correct it or contact LoginRadius support at <b><a href ="http://www.loginradius.com" target = "_blank">www.LoginRadius.com</a></b></p>';
      	}
	  else {
		$IsHttps = (!empty($UserAuth->IsHttps)) ? $UserAuth->IsHttps : '';
		$iframeHeight = (!empty($UserAuth->height)) ? $UserAuth->height : 50;
		$iframeWidth = (!empty($UserAuth->width)) ? $UserAuth->width : 138;
		$http = ($IsHttps == 1) ? "https://" : "http://";
		$loc = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK)."sociallogin/";
		echo '<div style="margin:5px"><div style="margin-bottom:5px">'.$loginRadiusTitle.'</div><iframe src="'.$http.'hub.loginradius.com/Control/PluginSlider.aspx?apikey='.$ApiKey.'&callback='.$loc.'" width="'.$iframeWidth.'" height="'.$iframeHeight.'" frameborder="0" scrolling="no" allowtransparency="true"></iframe></div>';
	  }
    echo '</p></div></div>';
  }
}
?>